### ISSUE TITLE
Housekeeping: Cloudfront instances should have access to S3 templated

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#3963]
**Background context or User story:**

_See https://stackoverflow.com/questions/54711268/giving-originaccessidentity-reference-in-cloudformation-or-serverless-yml it should be possible for us to template access control relationships between CloudFront and S3 for our web apps_

**Specification or Acceptance Criteria:**

- Should be applied to all web app templates
- https://aws.amazon.com/premiumsupport/knowledge-center/s3-rest-api-cloudfront-error-403/
- Relates to #5657

**Comment by willmcvay** [comment]
Tried the following config but getting an access denied error on the resource

```
service: cloud-geo-diary
plugins:
  - serverless-single-page-app-plugin
  - serverless-deployment-bucket
  - serverless-s3-remover
  - serverless-s3-deploy

custom:
  s3WebAppBucket: cloud-geo-diary-web-app-${opt:stage, 'dev'}
  s3CloudFormBucket: cloud-deployment-cloudform-templates-${opt:stage, 'dev'}
  remover:
    buckets:
      - ${self:custom.s3WebAppBucket}
  assets:
    auto: true
    targets:
      - bucket: ${self:custom.s3WebAppBucket}
        files:
          - source: ./public/dist/
            globs: '**/*'
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource: { 'Fn::Join': ['', ['arn:aws:s3:::', { 'Ref': 'WebAppS3Bucket' }]] }
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - 'Ref': 'WebAppS3Bucket'
            - '/*'

  deploymentBucket:
    name: ${self:custom.s3CloudFormBucket}

resources:
  Resources:
    ## Specifying the S3 Bucket
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3WebAppBucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    ## Specifying the policies to make sure all files inside the Bucket are available to CloudFront
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal:
                AWS:
                  Fn::Join: ['', ['origin-access-identity/cloudfront/', { 'Ref': 'WebAppOriginAccessIdentity' }, '/*']]
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ['', ['arn:aws:s3:::', { 'Ref': 'WebAppS3Bucket' }, '/*']]

    ## Specifying the CloudFront Distribution to server your Web Application
    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName:
                Fn::Join: ['', [{ 'Ref': 'WebAppS3Bucket' }, '.s3.amazonaws.com']]
              Id: S3-${self:custom.s3WebAppBucket}
              ## In case you want to restrict the bucket access use S3OriginConfig and remove CustomOriginConfig
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join: ['', ['origin-access-identity/cloudfront/', { 'Ref': 'WebAppOriginAccessIdentity' }, '/*']]
          Enabled: 'true'
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 400
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: S3-${self:custom.s3WebAppBucket}
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: 'true'
          # Logging:
          #   IncludeCookies: 'false'
          #   Bucket: mylogs.s3.amazonaws.com
          #   Prefix: myprefix

    WebAppOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'Access for Cloudfront to S3 Webapp bucket'
  Outputs:
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [WebAppCloudFrontDistribution, DomainName]
```
