### ISSUE TITLE
NavResponsive background colour inconsistent between

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#9097]
**Describe the bug**
The background colour of the icons in the sidebar seems to be inconsistent between between desktop and web.

Currently our app for the reapit marketplace uses `@reapit/elements` 3.8.2

When trying to update the package version a few months back to 3.11.1 we notice that the background colours for the icons were off

In the desktop, the background colour is absent - see screenshot 1

In the web-app, the background colour is present - see screenshot 2

This issue have been consistent across subsequent versions

**Expected behaviour**

**Screenshots**
1. This is the desktop app
<img width="90" alt="Screenshot 2023-05-19 at 09 20 10" src="https://github.com/reapit/foundations/assets/109656933/4063b98a-9931-4c7d-9f36-b44bc94d7a17">

2. This is the web app
![Screenshot 2023-05-19 at 10 16 08](https://github.com/reapit/foundations/assets/109656933/fdd1fdb5-ce16-4ca3-9159-416af66d9847)

**Device:**
 - Device: Mac
 - OS: Ventura 13.3.1 
 - Browser: Brave
 - Version v1.51.118

**Additional context**
This behaviour has been consistent across browsers, browser version, mac os versions

**Comment by bashleigh** [comment]
Hello @nikolai-momot-thirdfort The Pull Request I just made only fixes one icon (the appsMenu icon) where the fill property was not correct. However I don't think this is related to your primary problem. Are you using React or CSS classes of elements? If it's the latter you will need to ensure you have applied the class `el-nav-is-desktop` to your nav or if using custom CSS vars, make sure the svg fill vars are defined which I believe you do if you are using the stylesheet. 

I reckon you'll need to apply the CSS class `el-nav-is-desktop` to the nav. However the PR I've just created will fix the `appsMenu` icon so bare in mind that icon will likely not change colour theme

https://elements.reapit.cloud/?path=/docs/nav--theming-nav#theming-nav

https://elements.reapit.cloud/?path=/docs/nav--desktop-mode


If you've added custom CSS vars, below are the vars used for desktop.
```css
--nav-menu-icon-primary-accent: var(--intent-primary);
--nav-menu-icon-secondary-accent: var(--intent-secondary);


.el-nav-item:hover {
  --nav-menu-icon-primary-accent: var(--color-white);
  --nav-menu-icon-secondary-accent: var(--intent-primary);
}
```

If this doesn't solve your problem, please get back to us with some examples of your implementation.
